#!/usr/bin/env node
'use strict'

const program = require('commander');

program
  .usage('<extractor_component_name>')
  .version(require(`${__dirname}/package.json`).version, '-v, --version')
  .parse(process.argv);

require(".")(program.args[0]);
